### ISSUE TITLE
What're us app name?

### ISSUE THREAD

**Issue by TrungNguyen070191** [TrungNguyen070191/PJI#5]

**Comment by tranminhtrong** [comment]
Name: Let's Survey

**Comment by trongtranminh** [comment]
- [x] Let's Survey

- [ ] Let's Vote

- [x] Vote your best

- [ ] Choose your best

**Comment by TrungNguyen070191** [comment]
- [x]  Vote Now

- [x] My Vote

**Comment by trongtranminh** [comment]
Final app name is "Vote Now".
